### ISSUE TITLE
feat: 개인 목표 설정

### ISSUE THREAD

**Issue by dandamdandam** [LetsExercise/dailypet#14]
## 필요한 기능
- 개인 목표 설정 기능
- 목표 설정 방법
  |firebase users 컬랙션의 personalGoals 필드| workout 수정 사항 |
  |:---:|:---:|
  |![image](https://github.com/user-attachments/assets/55c79cfa-06b5-4446-8a24-f7cae188e416)|![image](https://github.com/user-attachments/assets/35f9c3c2-840e-42f1-bbf2-f71971690581)|

  - 수면: 목표 시작/끝 시간
  - 식단: 하루 목표 칼로리, 식단 라벨(ex 아침, 점저 ...)+시간
  - 운동: 어............ 제안 받아요

## 해야 할 일 
- [x] 테이블 추가
- [x] 각 스켈레톤 뷰 제작(수면->식단->운동 순)
- [x] session strage 추가(설정 내용 임시저장)
- [x] 설정 api (post)
- [x] 설정 api (get)

**Comment by Mule129** [comment]
운동의 경우 운동 시간, 운동 종류(개수) 로 가는게 제일 간편할 것 같습니다! 아니면 GPT 이용해서 운동의 강도에 따른 점수 정도..?

**Comment by dandamdandam** [comment]
> 운동의 경우 운동 시간, 운동 종류(개수) 로 가는게 제일 간편할 것 같습니다! 아니면 GPT 이용해서 운동의 강도에 따른 점수 정도..?

일주일 단위로 계획을 짜는 사람도 분명 있을 것 같아서요!
n요일 n시 ~ n시 정도로 목표를 짜게 해볼까요

**Comment by dandamdandam** [comment]
이전에 저장해두었던 설정 값을 초기 값으로 인풋에 불러오는 기능을 sessionStorage를 활용해 넣으려고 했으나 좀 복잡해서 구현안하고 미룹니다
