### ISSUE TITLE
디벨롭에 그냥 push 해버렸어요

### ISSUE THREAD

**Issue by dandamdandam** [LetsExercise/dailypet#17]
![image](https://github.com/user-attachments/assets/77a90e36-4bae-4142-a718-3752c56d445a)

체크아웃을 안했습니다.........
제안을 하려고 했는데 뭔가 강제 적용이 되어버렸네요

[이건 어때요](https://github.com/LetsExercise/dailypet/commit/6cf8844ad6306faee38bd9c16b6314965a0c9bc1)

네비게이션을 아래에 고정하고, 페이지는 그대로 스크롤 할 수 있게 했습니다.
컨텐츠가 부족해서 height가 남는 페이지의 경우는 나중에 `height: 100vh` 설정해주면 좋을 것 같아요.

@castberry10 @Mule129

**Comment by castberry10** [comment]
확인했습니다

**Comment by Mule129** [comment]
수고하셨습니다! 네비 만들때 이러한 요소도 적용할걸 단담님 덕분에 좋은 아이디어 얻어가는군요..

**Comment by dandamdandam** [comment]
좋게 받아들여져서 다행이네요...ㅎㅎ 이슈 닫겠습니다!
