### ISSUE TITLE
점수 구하기

### ISSUE THREAD

**Issue by castberry10** [LetsExercise/dailypet#18]
## 필요한 기능
- 밥, 잠, 운동으로 점수를 산정하는 기능
gpt를 쓰거나 어떻게 구현할지 고민해봐야합니다

## 해야 할 일 
- [ ] 점수 구현

## 추가 컨텍스트
- 추가로 해야 할 말이 있으면 작성해주세요

**Comment by Mule129** [comment]
현재로서는 [ 달성률 / 개인목표 ] 로 나눠서 점수 계산하는게 제일 간편하지 않을까 싶습니다

**Comment by dandamdandam** [comment]
gpt를 써봅시다
